version: "3"
services:
    web:
        build: .
        ports:
            - "5002:5002"
        depends_on:
            - db
    db:
        build: ../../../dbDocker
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"

